### ISSUE TITLE
ValueError: can't have unbuffered text I/O

### ISSUE THREAD

**Issue by liyao001** [liyao001/BioQueue#4]
Error might occur when executing bioqueue_daemon.py under Python 3, the error trace may like this:
```
Traceback (most recent call last):
  File "bioqueue_daemon.py", line 23, in <module>
    daemon_runner = runner.DaemonRunner(app)
  File "/Share/home/anaconda3/lib/python3.6/site-packages/daemon/runner.py", line 120, in __init__
    app.stderr_path, 'w+t', buffering=0)
ValueError: can't have unbuffered text I/O
```

**Comment by liyao001** [comment]
Switch to Python 2.7.
